#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : image
Version  : 1.5.27
Release  : 5
URL      : https://files.pythonhosted.org/packages/d1/e9/2ee43d1df1c19ac95a7e7547ad8b4b189536a520683e393ca02a1f2be38a/image-1.5.27.tar.gz
Source0  : https://files.pythonhosted.org/packages/d1/e9/2ee43d1df1c19ac95a7e7547ad8b4b189536a520683e393ca02a1f2be38a/image-1.5.27.tar.gz
Summary  : Django application that provides cropping, resizing, thumbnailing, overlays and masking for images and videos with the ability to set the center of attention,
Group    : Development/Tools
License  : BSD-3-Clause
Requires: image-python3
Requires: image-license
Requires: image-python
BuildRequires : buildreq-distutils3

%description
Please visit https://github.com/francescortiz/image

%package license
Summary: license components for the image package.
Group: Default

%description license
license components for the image package.


%package python
Summary: python components for the image package.
Group: Default
Requires: image-python3 = %{version}-%{release}

%description python
python components for the image package.


%package python3
Summary: python3 components for the image package.
Group: Default
Requires: python3-core

%description python3
python3 components for the image package.


%prep
%setup -q -n image-1.5.27

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1539121783
python3 setup.py build

%install
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/doc/image
cp LICENSE %{buildroot}/usr/share/doc/image/LICENSE
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/doc/image/LICENSE

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
